# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 884c585c0f3ebac65d4626a45db2dc38c5b4dfa935513e8d2e5cd6f9aa9dba0575b23dc9d9bde865a7c3032f55723947033a32a23ebfbdca497936013a5db031

test:
  secret_key_base: d7e83b87a8a2caeffba85938a1ffadefe6968059a65c2ec413c3f938fd9fe2a7da150138510c0279bd9c84b1a1af2622e0bc932d0a8a59c4f0700ca0ba21df2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
